In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[3,4],[4,5],[8,9],[5,5]])   #input
y = np.array([7,9,17,10])                 #output

In [ ]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [ ]:
print(round(model.predict([[1,2]])[0],0))

3.0

In [ ]:
model.predict([[10,10]])

array([20.])

In [ ]:
print(f"f(x) = {model.coef_[0]} *x1 + {model.coef_[1]} *x2")

f(x) = 0.9999999999999994 *x1 + 1.0000000000000002 *x2

In [ ]:
model.intercept_

np.float64(1.7763568394002505e-15)

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"mymodel")

['mymodel']

In [ ]:
model.score(X,y)

1.0

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("/content/iris.csv")

In [ ]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [ ]:
X = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]  #input
y = df['variety']                                                      #output

In [ ]:
X.shape

(150, 4)

In [ ]:
y.shape

(150,)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape

(120, 4)

In [ ]:
X_test.shape

(30, 4)

In [ ]:
y_train.shape

(120,)

In [ ]:
y_test.shape

(30,)

In [ ]:
X_train

     sepal.length  sepal.width  petal.length  petal.width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [ ]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_from_model = lr.predict(X_test)

In [ ]:
y_from_model

array(['Versicolor', 'Setosa', 'Virginica', 'Versicolor', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Versicolor',
       'Virginica', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Virginica', 'Virginica',
       'Virginica', 'Virginica', 'Setosa', 'Setosa'], dtype=object)

In [ ]:
y_test

73     Versicolor
18         Setosa
118     Virginica
78     Versicolor
76     Versicolor
31         Setosa
64     Versicolor
141     Virginica
68     Versicolor
82     Versicolor
110     Virginica
12         Setosa
36         Setosa
9          Setosa
19         Setosa
56     Versicolor
104     Virginica
69     Versicolor
55     Versicolor
132     Virginica
29         Setosa
127     Virginica
26         Setosa
128     Virginica
131     Virginica
145     Virginica
108     Virginica
143     Virginica
45         Setosa
30         Setosa
Name: variety, dtype: object

In [ ]:
lr.score(X_train,y_train)

0.975

In [ ]:
lr.score(X_test,y_test)

1.0

In [ ]:
X_test

     sepal.length  sepal.width  petal.length  petal.width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4
31            5.4          3.4           1.5          0.4
64            5.6          2.9           3.6          1.3
141           6.9          3.1           5.1          2.3
68            6.2          2.2           4.5          1.5
82            5.8          2.7           3.9          1.2
110           6.5          3.2           5.1          2.0
12            4.8          3.0           1.4          0.1
36            5.5          3.5           1.3          0.2
9             4.9          3.1           1.5          0.1
19            5.1          3.8           1.5          0.3
56            6.3          3.3           4.7          1.6
104           6.5          3.0           5.8          2.2
69            5.6          2.5           3.9          1.1
55            5.7          2.8           4.5          1.3
132           6.4          2.8           5.6          2.2
29            4.7          3.2           1.6          0.2
127           6.1          3.0           4.9          1.8
26            5.0          3.4           1.6          0.4
128           6.4          2.8           5.6          2.1
131           7.9          3.8           6.4          2.0
145           6.7          3.0           5.2          2.3
108           6.7          2.5           5.8          1.8
143           6.8          3.2           5.9          2.3
45            4.8          3.0           1.4          0.3
30            4.8          3.1           1.6          0.2

In [ ]:
lr.predict([[6.1,2.8,	4.7,	1.2]])  # column vector learned model

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Versicolor'], dtype=object)